### train configuration

exp_dir: exp/Voxceleb1-ECAPA_TDNN_GLOB_c1024-ASTP-emb192-FusionConcat_fbank80_WavLM_Large_frozen-num_frms150-aug0.6-spTrue-saFalse-ArcMargin_intertopk_subcenter-SGD-epoch150
gpus: "[0,1,2,3]"
num_avg: 10
enable_amp: True  

seed: 42
num_epochs: 110
save_epoch_interval: 5
log_batch_interval: 100

dataloader_args:
  batch_size: 64
  num_workers: 16
  pin_memory: False
  prefetch_factor: 16  
  drop_last: True

dataset_args:
  sample_num_per_epoch: 0
  shuffle: True
  shuffle_args:
    shuffle_size: 2500
  filter: True
  filter_args:
    min_num_frames: 50  
    max_num_frames: 400 
  resample_rate: 16000
  speed_perturb: True
  num_frms: 150  
  aug_prob: 0.6
  use_fusion: True  
  frontend: "s3prl"  
  s3prl_args:
    upstream_args:
      name: "wavlm_large"
    download_dir: ./s3prl_hub
    multilayer_feature: True
    layer: -1
    frozen: True
    frame_shift: 20
    frame_length: 20
  fbank_args:  
    num_mel_bins: 80
    frame_shift: 10
    frame_length: 25
    dither: 1.0
  cmvn: True
  cmvn_args:
    norm_mean: True
    norm_var: False  
  spec_aug: False
  spec_aug_args:
    num_t_mask: 1
    num_f_mask: 1
    max_t: 10
    max_f: 8
    prob: 0.6

model: ECAPA_TDNN_GLOB_c1024
model_init: null
model_args:
  feat_dim: 80  
  embed_dim: 192
  pooling_func: "ASTP"

projection_args:
  project_type: "arc_margin_intertopk_subcenter" 
  scale: 32.0
  easy_margin: False

margin_scheduler: MarginScheduler
margin_update:
  initial_margin: 0.0
  final_margin: 0.2
  increase_start_epoch: 20
  fix_start_epoch: 40
  update_margin: True
  increase_type: "exp"

loss: CrossEntropyLoss
loss_args: {}

optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001

scheduler: ExponentialDecrease
scheduler_args:
  initial_lr: 0.05
  final_lr: 0.00001  
  warm_up_epoch: 6
  warm_from_zero: True